### PR TITLE
fix check_for_error

### PR DESCRIPTION
**Pull request by papajoker**
revue check_for_error in /lib/*
issue #58 

- change 9x  by if test then command; check_for_error; fi
- and add somes return function_menu

not test 

revert commits https://github.com/Chrysostomus/manjaro-architect/commit/601af4a976ec562d85ef0f46b5564ea4934b484d  https://github.com/Chrysostomus/manjaro-architect/commit/5ac298bb4aa6c62a0ebd46025a3e664c3f9466a5  https://github.com/Chrysostomus/manjaro-architect/commit/145eb02bb832e2fff795e2d8f982fc49340cf97a

### CODE REVIEW

**Comment by Chrysostomus** [comment]
Looking through this, the modifications seem like they should work. 

One potential issue I see is with copying vconsole.conf and pacman.conf: even if they are tried to copy and operation fails, this should not halt the base installation function. It should continue to the end despite errors.

**Comment by Chrysostomus** [comment]
Okay, it seems to somehow break partition mounting...

**Comment by Chrysostomus** [comment]
Aah, found the problem! 

```
        # Warn about formatting!
        if [[ $FILESYSTEM != $_FSSkip ]]; then
            DIALOG " $_FSTitle " --yesno "\n$_FSMount $FILESYSTEM\n\n! $_FSWarn1 $PARTITION $_FSWarn2 !\n\n" 0 0
            if (( $? != 1 )); then
                ${FILESYSTEM} ${PARTITION} >/dev/null 2>$ERR
                check_for_error "mount $PARTITION as $FILESYSTEM." $?
            else
                select_filesystem
            fi
        fi
```
The test for continuing is reversed, cancel proceeds and ok returns back

**Comment by papajoker** [comment]
yes i view but i can detect where in code , noting in log

**Comment by Chrysostomus** [comment]
Fixed now with abf6d9d

**Pull request merged**
