### PR TITLE
attempt on a non-recursive version

### PR DESCRIPTION
**Pull request by oberon-manjaro**
I have the impression that it runs more responsive now.
Also along the way I un-nested some remaining functions and added some little error catching.
Have fun with it! ;)
**manjaro-architect-exp** is in unstable now.
Just updated once more. Latest version is now **r224.g69231ca**.

### CODE REVIEW

**Comment by oberon-manjaro** [comment]
It turned out that there's apparently no need for the submenus to bee looping. They simply point back to their respective parents and it seems to work without problem.

**Comment by oberon-manjaro** [comment]
One strange thing I encountered is that when you interrupt gpg key refreshing with Ctrl+C you are thrown out of the application completely. That does not happen with any pacman or basestrap action.
No idea if there's anything that can be done about that.

**Comment by oberon-manjaro** [comment]
I just realize that there is still a problem with exiting. We jump back to somewhere else and only at the second attempt it is possible to exit properly :stuck_out_tongue: What can this be??

**Comment by Chrysostomus** [comment]
Testing systemd gnome with it now. Seems to be working, Need to test exit navigation still though, as that is where the issues come visible.

**Comment by Chrysostomus** [comment]
A side effect: this structure allows accessing submenus without partition mounted or base installed. 'you do get a warning though

**Comment by Chrysostomus** [comment]
After many cancel actions I get into infinite loop when trying to exit installer

**Comment by Chrysostomus** [comment]
The gnome installation was very broken. Everything seemed to be fine in the installer, but the whole $HOME was owned by root, so gui filed to start. I think this bug was exposed, because user account was generated before desktop-settings was installed.

**Comment by oberon-manjaro** [comment]
It's strange that check_mount and check_base are not doing what they should
```
check_mount() {
    if [[ $(lsblk -o MOUNTPOINT | grep ${MOUNTPOINT}) == "" ]]; then
        DIALOG " $_ErrTitle " --msgbox "$_ErrNoMount" 0 0
        main_menu
    fi
}
```
should bring you straight back to main_menu, no?

I was trying hard to understand what's going on with exiting the installer and why it keeps bringing you back to random places. I didn't figure it out. It is a behaviour I get in the old version, too! I kept thinking that it has something to do with ``umount_partitions`` but all looks right there. It's like earlier processes are not quitting properly... something we still miss with error handling?

**Comment by Chrysostomus** [comment]
Opening of random menus was the result of other functions calling main_menu instead of exiting. No other menu should call main_menu. Otherwise something like this happens:

- I go open a submenu from main. This submenu has not replaced the original main menu process, it is a part of it.
- any function in submenu calls main menu. Now, this new main menu is sub process of that submenu. So when I exit the main menu, the script doesn't stop. It just continues the submenu in the place where the process left.
- if the submenu exits by calling main_menu again, we don't get to the original main menu, but a new one. 
- the script can only be exited by exiting the original main menu 

This my understanding of the problem.

**Comment by Chrysostomus** [comment]
At least check_mount, check_base and check_for_error call main_menu. This is a potential cause of recursion.

**Comment by oberon-manjaro** [comment]
I understand the principle, yes. So can you give an example with ``check_mount()`` how it will bring us back to main_menu? Just ``return`` And same for the submenus?

**Comment by Chrysostomus** [comment]
Check_mount: if true, call the submenu. If false, show message. Looping of the main menu takes care of the rest.

**Comment by oberon-manjaro** [comment]
what about check_for_error function? Isn't that recursive aswell?

**Comment by oberon-manjaro** [comment]
what's the right way to just do nothing and return to main_menu?
if check_mount just displays the error and lets us return, $ANSWER will still contain the selected value and the submenu will open. But when we change it to another value it will quit main_menu.

**Comment by oberon-manjaro** [comment]
will something like ``return 1`` from the check function work?

**Comment by oberon-manjaro** [comment]
```
check_mount() {
    if [[ $(lsblk -o MOUNTPOINT | grep ${MOUNTPOINT}) != "" ]]; then
        return 0
    else
        DIALOG " $_ErrTitle " --msgbox "$_ErrNoMount" 0 0
        return 1
    fi
}
```
and in main_menu:
```
"3") [[ check_base ]] && config_base_menu
                ;;
```

**Comment by oberon-manjaro** [comment]
I just can't figure out how to do it for all answers ``-eq 2`` or ``-ge 3`` at once - similar to what it is currently... :wink:

**Comment by oberon-manjaro** [comment]
what if check_base just sets ANSWER=2 and check_mount (to be called after check_base in that case) sets ANSWER=1 ?

**Comment by Chrysostomus** [comment]
Make Check_mount and check_base into wrapper functions. Possibly combine into one. They would be called like this:

       check_mount submenu_function_name

If check succeeds, call submenu_function_name. If it fails, display information dialog (Mount partitions first!"). After displaying the message, the script returns automatically to main menu because of the loop.

**Comment by oberon-manjaro** [comment]
```
if [[ $(cat ${ANSWER}) -ge 3 ]] && [[ $(cat ${ANSWER}) -le 8 ]]; then
           check_base
           check_mount
        fi
```
```
check_base() {
    if [[ ! -e /mnt/.base_installed ]]; then
        DIALOG " $_ErrTitle " --msgbox "$_ErrNoBase" 0 0
        ANSWER=2
    fi
}
```
```
check_mount() {
    if [[ $(lsblk -o MOUNTPOINT | grep ${MOUNTPOINT}) == "" ]]; then
        DIALOG " $_ErrTitle " --msgbox "$_ErrNoMount" 0 0
        ANSWER=1
    fi
}
```

**Comment by oberon-manjaro** [comment]
ah. and for something like ``install_bootloader()`` we'll still need a return code maybe
```
check_base() {
    if [[ ! -e /mnt/.base_installed ]]; then
        DIALOG " $_ErrTitle " --msgbox "$_ErrNoBase" 0 0
        ANSWER=2
        return 1
    else
        return 0
    fi
}
```
```
install_bootloader() {
    [[ check_mount ]] && [[ check_base ]] && {
        if [[ $SYSTEM == "BIOS" ]]; then
            bios_bootloader
        else
            uefi_bootloader
        fi
    }
}
```

**Comment by oberon-manjaro** [comment]
Let me know if that makes sense. If so I can make adjustment accordingly and remove all the "call-home" functions.
Still don't know how to deal with ``check_for_error()`` though.

**Comment by Chrysostomus** [comment]
Seems kind of complicated for me. I'll try to cook up something too.

**Comment by oberon-manjaro** [comment]
:wink: you're right. didn't see you other posts about wrapper funcions at first ...

**Comment by oberon-manjaro** [comment]
we can just drop the check depending on number and instead use the wrapper functions in the case statements for each submenu.

**Comment by oberon-manjaro** [comment]
what I thought is kind of nice is if the check functions bring us directly to the necessary submenu to mount of install base - or is that too annoying maybe?

**Comment by oberon-manjaro** [comment]
another advantage of the maybe more complicated way I posted above is that HIGHLIGHT will correctly be adjusted automatically. So in case you didn't install base you'll be transported back to prep_menu and when you return afterward you will be again at the next required step instead of where you wrongly attempted to go in the first place.

**Comment by oberon-manjaro** [comment]
ah, in fact the syntax for the check as described above is even simpler:
you can just do 
```
"3") check_mount && check_base && config_base_menu
                ;;
```

**Comment by oberon-manjaro** [comment]
in face check_base can simply include check_mount, since we never need to check base without needing mount aswell ;)

**Comment by Chrysostomus** [comment]
It kinda already does, since check for /mnt/.* fails if mnt is not mounted.

**Comment by oberon-manjaro** [comment]
Right. I've adjusted util and util-menu. Will do the other files a little later and then check if the baby is still alive ... :wink:

**Comment by Chrysostomus** [comment]
I marked all parts that seem to call parent function with '# Recurse'. Man, this going to take some time... Especially all the Arch installation related stuff (unconfigured desktop, networking and multimedia stuff...) is riddled with those. And I did not even mark check_for_error stuff, because you seem to have disabled the menu switching from there.

Also, just removing them seems not to be enough, because not all the menus are yet ready for this. I got some weird behavior in "Configure base" menu, and after installing base I was dropped to main_menu without error.

**Comment by oberon-manjaro** [comment]
seems at least you didn't find the need to mark anything in the two files I have processed sofar - I'll take it as a good sign :laughing: 
For me it's a good opportunity to get to know the code better and also like already the whole time this is such a huge and exciting learning experince for me that I don't mind going through the whole stuff again - I'm really enjoying it! :smile: 
Stay tuned!
In check_for_error I have disabled the function call of arg 3 but my theory was that since $3 is still used in assigning the local var it shouldn't complain, even if we miss some 3 arg calls to the function somewhere now. It should just be ignored. ...
We shall see!
:oncoming_police_car:

**Comment by Chrysostomus** [comment]
I'm now testing a version with unconfigured desktops and other arch specific stuff disabled. If we do that for the time being, we can get a working system faster. What's your opinion on that?
2017-03-02-005350_1920x1080_scrot

**Comment by Chrysostomus** [comment]
We could then re-add the disabled parts once we get those fixed. Or alternatively we could just take the installer to a simpler direction...

**Comment by Chrysostomus** [comment]
I think first level submenus should also loop like the main menu does. I think that would prevent the user being thrown back to main menu when for example base install completes.

**Comment by oberon-manjaro** [comment]
sounds like a good idea! I'm currently digging through util-base. Can you meanwhile commit those changes for the menus in util-menu and util-desktop? when the basic stuff is done we can then test how it works at all and then start readding the other things.

**Comment by oberon-manjaro** [comment]
for some menus this will certainly be helpful. there's probably no need to apply to all. currently at create user menu it will be very helpful. I'll do it there now already :+1:

**Comment by oberon-manjaro** [comment]
also install_base will be easier like that

**Comment by Chrysostomus** [comment]
I pushed the changes. However, util-disk.sh is still very much a mess. I think we have the biggest work there.

**Comment by oberon-manjaro** [comment]
I'm a little confused with this... Can you have a look, please?
I think using a subloop like I did here is the only way to get out of the password loops (at all those ``2>${ANSWER} ||``-places) to the parent menu (config_base_menu) ... or is it?
```
create_new_user() {
    declare -i loopmenu=1
    while ((loopmenu)); do
        DIALOG " $_NUsrTitle " --inputbox "$_NUsrBody" 0 0 "" 2>${ANSWER} || loopmenu=0
        USER=$(cat ${ANSWER})

        # Loop while user name is blank, has spaces, or has capital letters in it.
        while [[ ${#USER} -eq 0 ]] || [[ $USER =~ \ |\' ]] || [[ $USER =~ [^a-z0-9\ ] ]]; do
            DIALOG " $_NUsrTitle " --inputbox "$_NUsrErrBody" 0 0 "" 2>${ANSWER} || loopmenu=0
            USER=$(cat ${ANSWER})
        done

        DIALOG "$_DefShell" --radiolist "\n\n$_UseSpaceBar" 0 0 3 \
          "zsh" "-" on \
          "bash" "-" off \
          "fish" "-" off 2>/tmp/.shell
          shell=$(cat /tmp/.shell)

        # Enter password. This step will only be reached where the loop has been skipped or broken.
        DIALOG " $_ConfUsrNew " --clear --insecure --passwordbox "$_PassNUsrBody $USER\n\n" 0 0 \
          2> ${ANSWER} || loopmenu=0
        PASSWD=$(cat ${ANSWER})

        DIALOG " $_ConfUsrNew " --clear --insecure --passwordbox "$_PassReEntBody" 0 0 \
          2> ${ANSWER} || loopmenu=0
        PASSWD2=$(cat ${ANSWER})

        # loop while passwords entered do not match.
        while [[ $PASSWD != $PASSWD2 ]]; do
            DIALOG " $_ErrTitle " --msgbox "$_PassErrBody" 0 0

            DIALOG " $_ConfUsrNew " --clear --insecure --passwordbox "$_PassNUsrBody $USER\n\n" 0 0 \
              2> ${ANSWER} || loopmenu=0
            PASSWD=$(cat ${ANSWER})

            DIALOG " $_ConfUsrNew " --clear --insecure --passwordbox "$_PassReEntBody" 0 0 \
              2> ${ANSWER} || loopmenu=0
            PASSWD2=$(cat ${ANSWER})
        done

        # create new user. This step will only be reached where the password loop has been skipped or broken.
        DIALOG " $_ConfUsrNew " --infobox "$_NUsrSetBody" 0 0
        sleep 2

        # Create the user, set password, then remove temporary password file
        arch_chroot "groupadd ${USER}"
        arch_chroot "useradd ${USER} -m -g ${USER} -G wheel,storage,power,network,video,audio,lp -s /bin/$shell" 2>$ERR
        check_for_error "add user to groups" $?
        echo -e "${PASSWD}\n${PASSWD}" > /tmp/.passwd
        arch_chroot "passwd ${USER}" < /tmp/.passwd >/dev/null 2>$ERR
        check_for_error "create user pwd" $?
        rm /tmp/.passwd

        # Set up basic configuration files and permissions for user
        #arch_chroot "cp /etc/skel/.bashrc /home/${USER}"
        arch_chroot "chown -R ${USER}:${USER} /home/${USER}"
        [[ -e ${MOUNTPOINT}/etc/sudoers ]] && sed -i '/%wheel ALL=(ALL) ALL/s/^#//' ${MOUNTPOINT}/etc/sudoers
        loopmenu=0
    done
}
```

**Comment by oberon-manjaro** [comment]
So that means wherever we currently use ``return 0`` in a submenu loop to exit to parent we should change that to ``break``?

**Comment by Chrysostomus** [comment]
I'm testing now systemd version of lxqt profile. Navigation in prep_menu works now as expected. Great job!

**Comment by Chrysostomus** [comment]
At least the basic version seems to be working extremely well now.

**Comment by Chrysostomus** [comment]
I'll test the advanced menu some more, but this seems to be soon ripe for merging.

**Comment by Chrysostomus** [comment]
The regular/advanced choice does not seem to be anything though. Both options lead to basic.

**Comment by oberon-manjaro** [comment]
Menu options switch fixed. It cost exactly [1 Dollar](https://github.com/oberon2007/manjaro-architect/commit/558e642f828955bd8d5c003c1945a54efc47a015#diff-5c18fa8b9d6058aa726cce2bcced7b28R33) :wink:

**Pull request merged**
