### PR TITLE
updated PKGBUILD

### PR DESCRIPTION
**Pull request by oberon-manjaro**

### CODE REVIEW

**Comment by oberon-manjaro** [comment]
uhm, don't know why all the edits are showing again now in this new PR. Actually it's just about the updated PKGBUILD :wink:

**Comment by oberon-manjaro** [comment]
Ah. NOW! :+1:

**Comment by oberon-manjaro** [comment]
I hope it's ok that I bumped the version... Package is already in unstable. Will test it now with icon, launcher and all :)

**Comment by oberon2007** [comment]
:smile:

**Pull request merged**
