### PR TITLE
ini file

### PR DESCRIPTION
**Pull request by papajoker**
.ini file to centralize all informations given by the machine and the user.

future:
- replace small files in /tmp/
- other log / information file
- possibility to reuse it: `manjaro-architect -f "file.ini"` for not to re-enter datas ?
- possibility to use it to run developer tests
- an independence of time between menus tree and the real installation?

----------

Easy to use, all in the box

- Write: `ini system.init "openrc"`
 - Read: `init=$(ini system.init)`

The file is copied from /tmp/ to /var/log/m-a.ini when the program is closed

------------

```
[manjaro-architect]
date = 03/13/17 06:34:47
version = test#@version@

[system]
lang = fr_FR.UTF-8
init = systemd
bios = BIOS

[linux]
font = ter-114n
keymap = fr

...
```

### CODE REVIEW

**Comment by Chrysostomus** [comment]
Looks awesome, and a major step forward!

**Comment by oberon-manjaro** [comment]
Questions:
* You use the filename, really??
``ini branch "$BRANCH"``
while ``BRANCH="/tmp/.branch"``
no cat needed?
* Can we overwrite content of ini just like variables?
So for example at one point we define ``ini branch 'stable'`` and then later some function changes it?
* Can ini be used with a function like for example:
``ini branch "$(grep -oE -m 1 "unstable|stable|testing" /etc/pacman.d/mirrorlist)"``

**Comment by oberon-manjaro** [comment]
It's apparently a mistake :wink: 
```
[manjaro-architect]
branch = /tmp/.branch
date = 03/13/17 22:32:30
version = 0.8.0
```

**Comment by oberon-manjaro** [comment]
https://github.com/Chrysostomus/manjaro-architect/commit/d9d51bf1c9fe15b9ae04b04bd1cb3dee4bcaeb9a

**Comment by oberon-manjaro** [comment]
Ok. I think all my questions have been answered :wink: 
I'm playing with this more.
I like it a lot!
Thank you, @papajoker ! :+1:

**Comment by papajoker** [comment]
Sorry, I did not realize it was a file!

The format ini is great but not practical for undefined lists when we want to re-read

For example with users

    [Users]
    1 = paul
    2 = raoul

This is not a good format, difficult to read or we make a loop from 1 to 99?

So in this example I opted for the whole list in the same item
It is easy to read but after you have to cut out the list ...

    Users = paul; raoul
    Shells = zsh; bash

Ps: I use as separator the ";" Because I do not know if it is possible to have spaces in the name?

[c47038c32d858beda9d08788fef2e36edecb8f15](Https://github.com/Chrysostomus/manjaro-architect/commit/c47038c32d858beda9d08788fef2e36edecb8f15)

**Pull request merged**
