### PR TITLE
Updated Polish translation

### PR DESCRIPTION
**Pull request by edskeye**
By an accident i've posted it to @Acidburn0zzz repo.
Sorry for that - don't know how to delete pull request - still GitHub noob.
Anyway how to translate this (there are no strings for this):
screenshot_1
screenshot_2

### CODE REVIEW

**Comment by oberon-manjaro** [comment]
Hi @edskeye At the very bottom of a pull request you should find a button to just close it.
Did you check the [latest English file](https://raw.githubusercontent.com/Chrysostomus/manjaro-architect/master/data/translations/english.trans)? We have added quite some to the old one!
the first string is [line 144](https://github.com/Chrysostomus/manjaro-architect/blob/master/data/translations/english.trans#L144) - which needs correction also in the original as I just see 😉 
the other is [line 275](https://github.com/Chrysostomus/manjaro-architect/blob/master/data/translations/english.trans#L275)
Thank you again for your contribution!

**Comment by oberon-manjaro** [comment]
Where and when exactly did you get your English original file? If you know that or if you still have your original we can maybe make a diff for you to easily see what is missing in yours.

**Comment by edskeye** [comment]
There are other stuff down there - not only mine. I don't want to mess more than i already did. 
I will check eneglish base at home and update everything that will require this.

**Comment by oberon-manjaro** [comment]
No problem. No hurry! And as I already said, lets make a diff from your original file. Looking for the new strings would be tedious work. I can help you with that if you like :)

**Comment by papajoker** [comment]
we have a bash [script](https://github.com/Chrysostomus/manjaro-architect/blob/master/bin/check-translate.in) for test translations
in local git clone, cd bin; `bash check-translate.in` ( is not a real .in, path "data" is hard coded - no reason to install in /bin/ for simple users)

```
-- polish.trans 0 to translate --
	_Keep not exist
	_Change not exist
	_LuksErr not exist
	_RankMirrors not exist
	_DefKeymap not exist
	_InstFail not exist
	_InstGrubBody not exist
	_DesktopInstalled not exist
	_PkgList not exist
	_InstFree not exist
	_SelDDrv not exist
	_RunMkinit not exist
	_RunUpGrub not exist
	_SelNWDrv not exist
```

**Comment by oberon-manjaro** [comment]
Yes! totally cool - I forgot about that ;) I thought it would only check for ``# translate me !`` string - my memory failed me ;)

**Comment by edskeye** [comment]
@papajoker  Whoa... looks like i don't understand something (i'm just a graphic designer, not a developer). Should i translate phrases you gave in the comment above or it's just an output of the script that gives me things that need to be translated as an update of polish.trans file?

**Comment by papajoker** [comment]
All rows are translated into the file
> -- polish.trans 0 to translate --

but, There are no 14 lines in your polish.trans file that begin with word :

> 	_Keep not exist
> 	_Change not exist
> 	_LuksErr not exist
> 	_RankMirrors not exist
> 	_DefKeymap not exist
> 	_InstFail not exist
> 	_InstGrubBody not exist
> 	_DesktopInstalled not exist
> 	_PkgList not exist
> 	_InstFree not exist
> 	_SelDDrv not exist
> 	_RunMkinit not exist
> 	_RunUpGrub not exist
> 	_SelNWDrv not exist

Copy them from [english.trans](https://github.com/Chrysostomus/manjaro-architect/blob/master/data/translations/english.trans#L24) file in your polish.trans
Your polish.trans file was out of date

**Comment by edskeye** [comment]
Yeah... noticed that when comparing translations i Atom. Sorry for "asking before thinking" :P

**Pull request merged**
