### PR TITLE
Select keymap automatically based on language selection

### PR DESCRIPTION
**Pull request by oberon-manjaro**
with dialog-option to set it manually

### CODE REVIEW

**Comment by oberon-manjaro** [comment]
Hm. Testing ini doesn't seem to work because values are not persistent from last run :wink: 
I guess for this kind of special need we have to still use tmp files... @papajoker ?

**Comment by oberon-manjaro** [comment]
Or do I have the option to read from **/var/log/m-a.ini**, which exists from the last run? It contains what I need (lang and keymap):
```
$ cat /var/log/m-a.ini

[manjaro-architect]
date = 03/20/17 11:40:11
version = 0.8.1

[system]
lang = en_US.UTF-8
branch = stable
init = systemd
bios = UEFI

[linux]
font = ter-116n
keymap = de
```

**Comment by oberon-manjaro** [comment]
I guess I will need [inifile()](https://github.com/Chrysostomus/manjaro-architect/commit/69e22316464d4d8687241cbf56e8cd74c6f3b6fe#diff-f1f0aaee6fe02e534e572e6ed87e8ba7R130) now ... ? :wink:

**Comment by papajoker** [comment]
its no persistent
for this moment, if we re-use ini, we must pass the ini file in parameter

    architect --ini="/var/log/m-a.ini"

in ini branch now we can reuse `base-install` and `mount-root` https://github.com/Chrysostomus/manjaro-architect/commit/f6c65eb7b5a40dab5b49c1767815d1d8b7687ca1#commitcomment-21392467

Attention, if a value exists, the dialog is not even displayed!

In the long term, this should help us to create a custom model for our own installation with a minimum of dialogs

----------------------------------

dont [use](https://github.com/Chrysostomus/manjaro-architect/blob/keymap/lib/util.sh#L212) : 

    if [[ ! $(ini system.lang) ]]; then dialog ...

but

     if [[ ! $(getvar system.lang) ]]; then dialog ...

[getvar](https://github.com/Chrysostomus/manjaro-architect/blob/ini/lib/util.sh#L139) read first console param, import ini pass by `--ini="file"` and at end curent ini in /tmp/
**It is this change that creates precisely persistence!**

    vars=$(getvar "base.modules") # get "persistent" var
    if [[ -z "${vars}" ]]; then
        dialog ... >$ANSWER
        vars=$(<ANSWER)
        ini "base.modules" "${vars}" # save in ini tmp file
    else
         echo "${vars}">$ANSWER
    fi

------------------

A "big" problem, Is that we can not go back, once a data in the file tmp ini, the dialog no longer appears ? :tired_face:
use a variable denytback=1 only in import ini ??? (Not a good solution)

    if [[ ! $(getvar system.lang) || $(getvar denytback) != '' ]]; then dialog ...

**Comment by oberon-manjaro** [comment]
I don't yet understand everything here ... :wink: Will think about all that more, later.

**Comment by oberon-manjaro** [comment]
So if I understand correctly for the normal current usecase where the app is launched without a special parameter [grepping /var/log/m-a.ini](https://github.com/Chrysostomus/manjaro-architect/pull/129/commits/43c08b822524e589239ce89bdeefefd0d4d8272e) looks like an ok way of checking if language and keymap have already been set on the host, right?
Maybe I should just add an option to change the settings anyway, because the user could have made a mistake on first run ... :wink:

**Comment by oberon-manjaro** [comment]
I think it works nicely now.

**Pull request merged**
